keys:
  - &admin_christian F1A1F1A33787F28359E60BFB1DBDE5EC541E1874
  - &computer_hydra age13sypr3ave32sf4lvzckwlj65mkmerzaxh856v8sy7s240hkldfaqmn2agn
  - &computer_alexandria age14hdf0lh8ykyqk48js6uyj3e8e43fjusnatrh8q5wt7tath3jsa5s5xr22s
  - &computer_ulysses age1lzpwgj240wsf24xa5lthpzsc6pgqwjp8tz4a75r2ss7du34ucsdscgp85n
  - &to_encrypt  '(aws|xandikos|private|secret|password|hashed)$'
creation_rules:
  - path_regex: computers/hydra/secrets.yaml$
    encrypted_regex: *to_encrypt
    key_groups:
    - pgp:
      - *admin_christian
      age:
      - *computer_hydra
  - path_regex: computers/alexandria/secrets.yaml$
    encrypted_regex: *to_encrypt
    key_groups:
    - pgp:
      - *admin_christian
      age:
      - *computer_alexandria
  - path_regex: computers/ulysses/secrets.yaml$
    encrypted_regex: *to_encrypt
    key_groups:
    - pgp:
      - *admin_christian
      age:
      - *computer_ulysses
