{
  config,
  disko,
  lanzaboote,
  lib,
  modulesPath,
  nixpkgs,
  pkgs,
  sops-nix,
  ...
}: {
  imports = [
    lanzaboote.nixosModules.lanzaboote
    disko.nixosModules.disko
    (modulesPath + "/installer/scan/not-detected.nix")
    sops-nix.nixosModules.sops
    ./sops.nix
    ../disko-config.nix
    ../shared-config.nix
    ../../modules/acme.nix
    ../../modules/pixiecore.nix
    ../../modules/postfix.nix
    ../../modules/serial-console.nix
  ];

  options.hydra = {
  };

  config = let
    byidpath = name: "/dev/disk/by-id/" + name;
    localdrives = map byidpath ["nvme-Samsung_SSD_970_EVO_Plus_2TB_S4J4NX0R847857X" "ata-SanDisk_SSD_PLUS_2000GB_213705800853"];
  in {
    boot = {
      bootspec.enable = true;
      loader.systemd-boot.enable = nixpkgs.lib.mkForce false;
      lanzaboote = {
        enable = true;
        pkiBundle = "/etc/secureboot";
      };
      initrd = {
        availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" "amdgpu"];
        kernelModules = ["amdgpu"];
      };
      kernelModules = ["kvm-amd"];
      extraModulePackages = [];
    };

    caacme = {
      enable = true;
      credentialsfile = config.sops.templates."route53Credentials".path;
    };
    cagitea = {
      enable = true;
      domain = "gitea.catbertsen.de";
    };
    canginx.enable = true;
    capixiecore.enable = true;
    capostfix = {
      enable = true;
      connection = "smtp.protonmail.ch:587";
      mydomain = "catbertsen.de";
    };
    casaned.enable = true;
    caserialconsole.enable = true;
    caxandikos = {
      enable = true;
      domain = "calendar.catbertsen.de";
      passwordfile = config.sops.templates."xandikosBasicAuth".path;
    };

    cadrives = {
      enable = true;
      boot = null;
      system = localdrives;
      storage = [];
      swapsize = "72G";
      l2arcsize = "0";
      espsize = "1G";
      homesFor = ["christian" "marianne"];
    };
    services = {
      xserver.videoDrivers = ["amdgpu"];
      systembus-notify.enable = true;
      smartd = {
        enable = true;
        autodetect = false;
        devices = map (drive: {device = drive;}) localdrives;
        notifications.systembus-notify.enable = true;
        notifications.mail = {
          enable = true;
          sender = "hydra@catbertsen.de";
          recipient = "christian@wudika.de";
        };
      };
    };
    nix.buildMachines = [
      {
        hostName = "mini.local";
        sshUser = "christianalbertsen";
        systems = ["aarch64-darwin" "aarch64-linux"];
        supportedFeatures = ["apple-virt" "nixos-test"];
      }
    ];

    services = {
      r53-ddns = {
        ttl = 3600;
        zoneID = "Z04260616D6EKM0EH83P";
        hostname = "hydra";
        environmentFile = config.sops.templates."route53Credentials".path;
        enable = true;
        domain = "catbertsen.de";
      };
      pcscd.enable = true;
      printing = {
        enable = true;
      };
    };

    networking = {
      firewall.enable = false;
      hostId = "b800626c";
      hostName = "hydra";
      useDHCP = lib.mkDefault true;
    };

    hardware = {
      cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
      graphics = {
        extraPackages = with pkgs; [
          libvdpau-va-gl
        ];
        extraPackages32 = with pkgs; [
          driversi686Linux.libvdpau-va-gl
        ];
      };
      printers = {
        ensurePrinters = [
          {
            name = "kyocera5021cdw";
            location = "Yorckstraße 38, Arbeitszimmer";
            deviceUri = "dnssd://Kyocera%20ECOSYS%20P5021cdw._ipp._tcp.local/?uuid=4509a320-0061-004d-0036-0025074fb3d9";
            model = "everywhere";
          }
        ];
        ensureDefaultPrinter = "kyocera5021cdw";
      };
    };
    environment = {
      systemPackages = with pkgs; [
        lm_sensors
        mokutil
        sbsigntool
        vulkan-validation-layers
      ];
      variables = {
        WLR_RENDERER = "vulkan";
      };
      etc."sysconfig/lm_sensors" = {
        text = ''
          # Generated by sensors-detect on Fri Feb 20 01:13:56 2026
          # This file is sourced by /etc/init.d/lm_sensors and defines the modules to
          # be loaded/unloaded.
          #
          # The format of this file is a shell script that simply defines variables:
          # HWMON_MODULES for hardware monitoring driver modules, and optionally
          # BUS_MODULES for any required bus driver module (for example for I2C or SPI).

          HWMON_MODULES="nct6775"
        '';
        user = "root";
        mode = "0644";
      };
    };

    system.stateVersion = "23.11";
  };
}
