{
  config,
  lib,
  modulesPath,
  overlays,
  pkgs,
  sops-nix,
  ...
}: {
  imports = [
    sops-nix.nixosModules.sops
    ./sops.nix
    (modulesPath + "/profiles/base.nix")
    ../shared-config.nix
    ../disko-config.nix
    ../../modules/acme.nix
    ../../modules/gitea.nix
    ../../modules/keyboard.nix
    ../../modules/nginx.nix
    ../../modules/pixiecore.nix
    ../../modules/postfix.nix
    ../../modules/saned.nix
    ../../modules/serial-console.nix
    ../../modules/sshd.nix
    ../../modules/usermount.nix
    ../../modules/users.nix
    ../../modules/wayland.nix
    ../../modules/xandikos.nix
    ../../modules/yubikey.nix
  ];

  options.hydra = {
  };

  config = let
    byidpath = name: "/dev/disk/by-id/" + name;
    localdrives = map byidpath ["nvme-Samsung_SSD_970_EVO_Plus_2TB_S4J4NX0R847857X" "ata-SanDisk_SSD_PLUS_2000GB_213705800853"];
  in {
    caacme = {
      enable = true;
      credentialsfile = config.sops.templates."route53Credentials".path;
    };
    cagitea = {
      enable = true;
      domain = "gitea.catbertsen.de";
    };
    cakeyboard.enable = true;
    canginx.enable = true;
    capixiecore.enable = true;
    capostfix = {
      enable = true;
      connection = "smtp.protonmail.ch:587";
      mydomain = "catbertsen.de";
    };
    casaned.enable = true;
    caserialconsole.enable = true;
    casshd.enable = true;
    causermount.enable = true;
    cawayland.enable = true;
    caxandikos = {
      enable = true;
      domain = "calendar.catbertsen.de";
      passwordfile = config.sops.templates."xandikosBasicAuth".path;
    };
    cayubikey.enable = true;

    cadrives = {
      enable = true;
      boot = null;
      system = localdrives;
      storage = [];
      swapsize = "72G";
      l2arcsize = "0";
      espsize = "1G";
      homesFor = ["christian" "marianne"];
    };
    services.systembus-notify.enable = true;
    services.smartd = {
      enable = true;
      autodetect = false;
      devices = map (drive: { device = drive; }) localdrives;
      notifications.systembus-notify.enable = true;
      notifications.mail = {
        enable = true;
        sender = "hydra@catbertsen.de";
        recipient = "christian@wudika.de";
      };
    };
    nix.buildMachines = [
      {
        hostName = "mini.local";
        sshUser = "christianalbertsen";
        systems = ["aarch64-darwin" "aarch64-linux"];
        supportedFeatures = ["apple-virt" "nixos-test"];
      }
    ];

    services = {
      r53-ddns = {
        ttl = 3600;
        zoneID = "Z04260616D6EKM0EH83P";
        hostname = "hydra";
        environmentFile = config.sops.templates."route53Credentials".path;
        enable = true;
        domain = "catbertsen.de";
      };
      avahi = {
        enable = true;
        nssmdns4 = true;
        nssmdns6 = true;
        publish = {
          enable = true;
          userServices = true;
          hinfo = true;
        };
        ipv6 = true;
      };
      pcscd.enable = true;
      resolved = {
        enable = true;
        dnssec = "true";
        domains = ["~."];
        fallbackDns = ["1.1.1.1#one.one.one.one.one" "1.0.0.1#one.one.one.one"];
        dnsovertls = "true";
      };
    };

    # environment.etc."sway/config.d/monitors.conf".text = ''
    #   output "DP-1" mode 3840x2160@30Hz pos 0 0
    #   output "HDMI-A-1" mode 1600x1200@60Hz pos 3840 0 scale 0.61
    # '';
    time.timeZone = "Europe/Berlin";
    i18n = {
      defaultLocale = "de_DE.UTF-8";
      extraLocaleSettings = {
        LC_COLLATE = "de_DE.UTF-8";
        LC_CTYPE = "de_DE.UTF-8";
      };
    };
    networking = {
      firewall.enable = false;
      nameservers = ["1.1.1.1#one.one.one.one" "1.0.0.1#one.one.one.one"];
      enableIPv6 = true;
      hostId = "b800626c";
      hostName = "hydra";
      tempAddresses = "disabled";
      # interfaces.enp2s0 = {
      #   ipv4.addresses = [
      #     {
      #       address = "192.168.10.254";
      #       prefixLength = 24;
      #     }
      #   ];
      # };
      # defaultGateway = {
      #   address = "192.168.10.1";
      #   interface = "enp2s0";
      # };
      # hosts = {
      #   "192.168.10.253" = [
      #     "mannahusum.catbertsen.de"
      #   ];
      #   "192.168.10.254" = [
      #     "hydra.catbertsen.de"
      #     "calendar.catbertsen.de"
      #     "gitea.catbertsen.de"
      #   ];
      # };

      useHostResolvConf = lib.mkForce false;
    };

    services.printing = {
      enable = true;
    };
    hardware.printers = {
      ensurePrinters = [
        {
          name = "kyocera5021cdw";
          location = "Yorckstraße 38, Arbeitszimmer";
          deviceUri = "dnssd://Kyocera%20ECOSYS%20P5021cdw._ipp._tcp.local/?uuid=4509a320-0061-004d-0036-0025074fb3d9";
          model = "everywhere";
        }
      ];
      ensureDefaultPrinter = "kyocera5021cdw";
    };
    environment.etc."sysconfig/lm_sensors" = {
      text = ''
        # Generated by sensors-detect on Fri Feb 20 01:13:56 2026
        # This file is sourced by /etc/init.d/lm_sensors and defines the modules to
        # be loaded/unloaded.
        #
        # The format of this file is a shell script that simply defines variables:
        # HWMON_MODULES for hardware monitoring driver modules, and optionally
        # BUS_MODULES for any required bus driver module (for example for I2C or SPI).

        HWMON_MODULES="nct6775"
      '';
      user = "root";
      mode = "0644";
    };

    environment.systemPackages = with pkgs; [
      file
      git
      git-crypt
      lm_sensors
      mokutil
      neovim
      ripgrep
      sbctl
      sbsigntool
      tpm2-tss
      xterm # for resize command
    ];
    system.stateVersion = "23.11";
  };
}
