
variable "iso_url" {
    type = string
    default = "https://channels.nixos.org/nixos-21.11/latest-nixos-minimal-x86_64-linux.iso"
}

variable "iso_checksum" {
    type = string
    default = "sha256:2e9a21fd8010934529aa1893543ee12a053916c917f1d75ec604bcd2f082d577"
}

variable "packer_cache" {
    type = string
    default = "./packer_cache"
}

source "qemu" "autogenerated_1" {
  communicator     = "ssh"
  ssh_username     = "nixos"
  ssh_password     = "nixos"
  ssh_certificate_file = "./sshkey"
  ssh_timeout      = "20m"
  accelerator      = "kvm"
  boot_wait        = "7s"
  disk_interface   = "virtio"
  disk_size        = "100G"
  format           = "raw"
  http_directory   = "httpd"
  iso_checksum     = "${var.iso_checksum}"
  iso_url          = "${var.iso_url}"
  machine_type     = "q35"
  net_device       = "virtio-net"
  output_directory = "nixos_test_build"
  qemuargs         = [
    ["-m", "4G" ],
    ["-smp", "6" ],
    ["-device", "virtio-blk-pci,drive=drive0,bootindex=0" ],
    ["-device", "virtio-blk-pci,drive=cdrom0,bootindex=1" ],
    ["-drive", "if=pflash,format=raw,readonly=on,file=/run/libvirt/nix-ovmf/OVMF_CODE.fd"],
    ["-drive", "if=pflash,format=raw,readonly=on,file=./OVMF_VARS.fd"],
    ["-drive", "if=none,file=${var.packer_cache}/${sha1(var.iso_checksum)}.iso,media=cdrom,id=cdrom0" ],
    ["-drive", "if=none,file=nixos_test_build/nixbox_minimal,cache=writeback,discard=ignore,format=raw,id=drive0" ]
  ]
  vm_name          = "nixbox_minimal"
  boot_command = [
    "<enter>",
    "<wait25s>",
    "install -d -m 700 -o nixos -g users .ssh<enter>",
    "curl http://{{ .HTTPIP }}:{{ .HTTPPort }}/sshkey.pub -o .ssh/authorized_keys<enter>",
    "chmod 600 .ssh/authorized_keys<enter>",
    "passwd<enter>",
    "nixos<enter>",
    "nixos<enter>"
    ]
}

build {
    sources = ["source.qemu.autogenerated_1"]

    provisioner "file" {
        source = "/etc/nixos/install3.sh"
        destination = "/tmp/install3.sh"
    }

    provisioner "file" {
        source = "/etc/nixos/passphrase.txt"
        destination = "/tmp/passphrase.txt"
    }

    provisioner "file" {
        source = "/etc/nixos/minimal.nix"
        destination = "/tmp/configuration.nix"
    }

    provisioner "shell" {
        inline = ["/tmp/install3.sh"]
    }

}
