# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "manna_ssd/NixOS/root";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "manna_spin/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/579e7ce5-0041-4d6d-b20a-a8d136bd95ee";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."mannassdboot".device = "/dev/disk/by-uuid/fcf837ac-43ba-4d30-b046-3098534c0833";

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/5577-A555";
      fsType = "vfat";
    };

  fileSystems."/boot0" =
    { device = "/dev/disk/by-uuid/181b2260-ceca-4b08-8179-3458b43a177c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."mannaspinboot0".device = "/dev/disk/by-uuid/e86bfe83-69c1-48f7-802c-bd20fc4b9352";

  fileSystems."/boot0/efi" =
    { device = "/dev/disk/by-uuid/60E4-CF04";
      fsType = "vfat";
    };

  fileSystems."/boot1" =
    { device = "/dev/disk/by-uuid/64b08752-47ea-4487-ad68-f6f5ee01a84f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."mannaspinboot1".device = "/dev/disk/by-uuid/5b8b41a8-2ac6-4dc5-952a-f1971c630433";

  fileSystems."/boot1/efi" =
    { device = "/dev/disk/by-uuid/6299-921F";
      fsType = "vfat";
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  hardware = {
    nvidia.prime = {
      sync.enable= true;
      nvidiaBusId = "PCI:1:0:0";
      intelBusId = "PCI:0:2:0";
    };
  };

}
